[versions]
agp = "8.5.0"
appcompat = "1.7.0"
fragment = "1.8.1"
navigation = "2.7.7"
preference = "1.2.1"
shapes = "1.0.0-beta01"
material = "1.13.0-alpha03"
kotlin = "2.0.0"
splashscreen = "1.1.0-rc01"
wear-input = "1.1.0"
wear-tooling = "1.0.0"
wear-ongoing = "1.0.0"
compose-bom = "2024.06.00"
compose-material = "1.0.0-alpha23"
compose-navigation = "1.4.0-beta03"
compose-foundation = "1.4.0-beta03"
compose-runtime = "1.7.0-beta04"
compose-activity = "1.9.0"
compose-constraintlayout = "1.0.1"
lifecycle = "2.8.2"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
shapes = { group = "androidx.graphics", name = "graphics-shapes-android", version.ref = "shapes" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
# wear
wear-tooling = { group = "androidx.wear", name = "wear-tooling-preview", version.ref = "wear-tooling" }
wear-ongoing = { group = "androidx.wear", name = "wear-ongoing", version.ref = "wear-ongoing" }
wear-input = { group = "androidx.wear", name = "wear-input", version.ref = "wear-input" }
lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycle" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "compose-runtime" }
compose-material = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "compose-material" }
compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "compose-foundation" }
compose-animation-graphics = { group = "androidx.compose.animation", name = "animation-graphics" }
compose-navigation = { group = "androidx.wear.compose", name = "compose-navigation", version.ref = "compose-navigation" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "compose-constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigation" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }